# Bag of Words and TF-IDF
Below, we'll look at three useful methods of vectorizing text.
- `CountVectorizer` - Bag of Words
- `TfidfTransformer` - TF-IDF values
- `TfidfVectorizer` - Bag of Words AND TF-IDF values

Let's first use an example from earlier and apply the text processing steps we saw in this lesson.

In [1]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer

nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

Use the skills you learned so far to create a function `tokenize` that takes in a string of text and applies the following:
- case normalization (convert to all lowercase)
- punctuation removal
- tokenization, lemmatization, and stop word removal using `nltk`

In [2]:
corpus = ["The first time you see The Second Renaissance it may look boring.",
        "Look at it at least twice and definitely watch part 2.",
        "It will change your view of the matrix.",
        "Are the human people the ones who started the war?",
        "Is AI a bad thing ?"]

In [3]:
def tokenizer(text) :
    
    # Normalization
    text = re.sub(r'[^a-zA-Z0-9]',' ', text.lower())
    
    # Tokenization
    words = word_tokenize(text)
    
#     # Remove stopwords
#     words = [w for w in words if not w in stopwords.words("english")]
    
#     # Lemmatize word
#     lemmatizer = WordNetLemmatizer()
#     result = [lemmatizer.lemmatize(word) for word in words]
    
    # REFACTOR - Lemmatize non-stopwords
    lemmatizer = WordNetLemmatizer()
    result = [lemmatizer.lemmatize(word) for word in words if not word in stopwords.words('english')]
    
    return result
    

In [4]:
tokenizer(corpus[0])

['first', 'time', 'see', 'second', 'renaissance', 'may', 'look', 'boring']

# `CountVectorizer` (Bag of Words)

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
# initialize count vectorizer object
vect = CountVectorizer(tokenizer=tokenizer)

In [28]:
# get counts of each token (word) in text data
X = vect.fit_transform(corpus)

In [29]:
# convert sparse matrix to numpy array to view
X.toarray()

array([[0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
        0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0]])

In [53]:
# view token vocabulary and counts
vect.vocabulary_

{'2': 0,
 'ai': 1,
 'bad': 2,
 'boring': 3,
 'change': 4,
 'definitely': 5,
 'first': 6,
 'human': 7,
 'least': 8,
 'look': 9,
 'matrix': 10,
 'may': 11,
 'one': 12,
 'part': 13,
 'people': 14,
 'renaissance': 15,
 'second': 16,
 'see': 17,
 'started': 18,
 'thing': 19,
 'time': 20,
 'twice': 21,
 'view': 22,
 'war': 23,
 'watch': 24}

# `TfidfTransformer`

In [30]:
from sklearn.feature_extraction.text import TfidfTransformer

In [31]:
# initialize tf-idf transformer object
transformer = TfidfTransformer(smooth_idf=False)

In [32]:
# use counts from count vectorizer results to compute tf-idf values
tfidf = transformer.fit_transform(X)

In [33]:
# convert sparse matrix to numpy array to view
tfidf.toarray()

array([[0.        , 0.        , 0.        , 0.36419547, 0.        ,
        0.        , 0.36419547, 0.        , 0.        , 0.26745392,
        0.        , 0.36419547, 0.        , 0.        , 0.        ,
        0.36419547, 0.36419547, 0.36419547, 0.        , 0.        ,
        0.36419547, 0.        , 0.        , 0.        , 0.        ],
       [0.39105193, 0.        , 0.        , 0.        , 0.        ,
        0.39105193, 0.        , 0.        , 0.39105193, 0.28717648,
        0.        , 0.        , 0.        , 0.39105193, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.39105193, 0.        , 0.        , 0.39105193],
       [0.        , 0.        , 0.        , 0.        , 0.57735027,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.57735027, 0.

# `TfidfVectorizer`
`TfidfVectorizer` = `CountVectorizer` + `TfidfTransformer`

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
# initialize tf-idf vectorizer object
vectorizer = TfidfVectorizer(tokenizer=tokenizer)

In [39]:
# compute bag of word counts and tf-idf values
X = vectorizer.fit_transform(corpus)

In [40]:
# convert sparse matrix to numpy array to view
X.toarray()

array([[0.        , 0.        , 0.        , 0.36152912, 0.        ,
        0.        , 0.36152912, 0.        , 0.        , 0.29167942,
        0.        , 0.36152912, 0.        , 0.        , 0.        ,
        0.36152912, 0.36152912, 0.36152912, 0.        , 0.        ,
        0.36152912, 0.        , 0.        , 0.        , 0.        ],
       [0.38775666, 0.        , 0.        , 0.        , 0.        ,
        0.38775666, 0.        , 0.        , 0.38775666, 0.31283963,
        0.        , 0.        , 0.        , 0.38775666, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.38775666, 0.        , 0.        , 0.38775666],
       [0.        , 0.        , 0.        , 0.        , 0.57735027,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.57735027, 0.